import { Button, ScrollView, TextEdit} from "std-widgets.slint";

component mymenu inherits Rectangle {
    in property <string> text;
    in property <length> mHeight;
    in-out property <bool> enabled;
    height: mHeight;
    callback menuClicked();

    item := VerticalLayout{
                alignment: space-around;
                Text {
                    font-size: 12px;
                    text: text; color:
                    root.enabled ? white : grey;
                }
    }

    touch := TouchArea{
        height: root.mHeight;
        width: root.width;
        clicked => {menuClicked()}
    }

}
export global TextContent {
    callback text_editted(string);
    in-out property <string> content;
    in-out property <string> word_count;

}
// menu callbacks
export global MyMenuCallback {
    callback new();
    callback save();
    callback save_as();
    callback redo();
    callback undo();
}

export component RxTextEdittor inherits Window {
    in-out property <int> word_count;
    in-out property <string> content;
    in-out property <bool> undo_enabled: false;
    in-out property <bool> redo_enabled: false;
    callback button_clicked;
    min-width: 480px;
    VerticalLayout {
        width: parent.width - 2px;
        height: parent.height - 2px;

        // Menu Bar
        menubar := Rectangle{
            height: 48px;
            background: #3d3d3d;
            HorizontalLayout {
                alignment: space-around;
                doBtn := HorizontalLayout {
                    alignment: end;
                    spacing: 20px;
                    undo := mymenu {
                        text: "Undo";
                        mHeight: parent.height;
                        enabled: root.undo_enabled;
                        menuClicked => {MyMenuCallback.undo(); textinput.text = root.content;}
                    }
                    redo := mymenu {
                        text: "Redo"; mHeight: parent.height;
                        enabled: root.redo_enabled;
                        menuClicked => {MyMenuCallback.redo(); textinput.text = root.content;}
                    }
                }
                menuitem := HorizontalLayout {
                    spacing: 20px;
                    alignment: end;
                    padding-right: -20px;
                    mymenu {text: "New"; mHeight: parent.height;menuClicked => {button_clicked()}}
                    mymenu {
                        text: "Save";
                        mHeight: parent.height;
                        menuClicked => {MyMenuCallback.save()}
                    }
                    mymenu {text: "Save as"; mHeight: parent.height;}
                }
            }

        }

        HorizontalLayout {
            Rectangle {
                background: green;
                width: 30px;
            }
            textinput := TextEdit {
                wrap: no-wrap;
                edited(text) => {
                    TextContent.text_editted(text);
                }
            }
        }

        statusbar := Rectangle{
            height: 30px;
            background: #2d2d2d;
            HorizontalLayout {
                mymenu {text:": words";}
             }
        }
    }
}